modify scripts to use shelper functions

diff --git a/.local/bin/cptusb b/.local/bin/cptusb
--- a/.local/bin/cptusb
+++ b/.local/bin/cptusb
@@ -5,22 +5,29 @@
 # copy over his USB will fit in
 #
 
-terminate() { printf "cptusb: %s\n" "$1" && exit 1 ; }
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
 
-[ $# -lt "2" ] && terminate "Not enough parameters" 
+[ $# -lt "2" ] && s_err "Not enough parameters" 
 
 files="$*"
 MPoint="${files##* }"
 
 # check if the mount point exists and if it is mounted
-[ ! -d "$MPoint" ] && terminate "$MPoint does not exists".
+[ ! -d "$MPoint" ] && s_err "$MPoint does not exists".
 [ -z "$(lsblk | grep "$MPoint")" ] &&
-    terminate "$MPoint is not mounted! Try again!"
+    s_err "$MPoint is not mounted! Try again!"
 
 files="${files% *}" # remove last argument(mount point)
 fileStatus=$(file $files)
 test "${fileStatus#*"No such file"}" != "$fileStatus" && 
-    terminate "$(printf "%s" "$fileStatus" | grep "No such file")"
+    s_err "$(printf "%s" "$fileStatus" | grep "No such file")"
 
 # take the spaces from usb and files
 usbFree=$(df | grep $MPoint | awk '{ print $4 }')
@@ -30,7 +37,7 @@ convertB() { printf "%s" "$1" | awk '{print $1/1024/1024 " GB "}' ; }
 
 # if the files are bigger than usb free space, print message
 [ "$fileSize" -gt "$usbFree" ] && 
-    terminate "The file that you wanna transfer is too big for the usb
+    s_err "The file that you wanna transfer is too big for the usb
 File: $(convertB "$fileSize") 
 Usb: $(convertB "$usbFree")"
 
@@ -40,4 +47,3 @@ notify() { sudo -u himynameisgarch DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path
 cp -gr $files $MPoint && 
     notify normal "Doom Guy says:" "Your files has been copied succesfully\nYou can unmount your usb now" && exit 1
 notify critical "Doom Guy says:" "Your files couldn't be copied"
-
diff --git a/.local/bin/csc b/.local/bin/csc
--- a/.local/bin/csc
+++ b/.local/bin/csc
@@ -9,8 +9,7 @@ if [ -f "$SHELPER" ]; then
     # shellcheck disable=SC1090,SC1091
     . "$SHELPER"
 else
-    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"
-    exit 1
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
 fi
 file="$1"
 [ -z "$file" ] && s_err "Cannot create empty file!"
diff --git a/.local/bin/dict b/.local/bin/dict
--- a/.local/bin/dict
+++ b/.local/bin/dict
@@ -10,7 +10,14 @@ helpmenu() {
     echo "  add   - to add a new word in dictionary."
     echo "  edit  - to edit the dictionary file."
 }
-error() { printf 'error: %s\n' "$1" && exit 1 ; }
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
 
 BASEDIR="$HOME/Media/Data/dict" # overwrite this location
 BDICT="$BASEDIR/dictionary"
@@ -93,7 +100,7 @@ start() {
     sed -r 's/\s*#.*//g; /^$/ d' "$BDICT" | shuf > "$DICT"
     # Check for file length
     LC="$(wc -l "$DICT")"
-    [ "${LC%% *}" -lt 10 ] && error "You need to have at least 10 pairs in your dictionary.
+    [ "${LC%% *}" -lt 10 ] && s_err "You need to have at least 10 pairs in your dictionary.
 Run 'dict add' or 'dict edit' to add some more!"
     # Start the actual game
     echo "Current file: ${BDICT##*/}"
@@ -147,5 +154,5 @@ case $1 in
     start | s) start ;;
     add   | a) addentry ;;
     edit  | e) editfile "$2" ;;
-    *) error "Option \"$1\" is invalid. Type 'dict help' for more information" ;; 
+    *) s_err "Option \"$1\" is invalid. Type 'dict help' for more information" ;; 
 esac
diff --git a/.local/bin/dmenu/mdisk b/.local/bin/dmenu/mdisk
--- a/.local/bin/dmenu/mdisk
+++ b/.local/bin/dmenu/mdisk
@@ -5,11 +5,18 @@
 # A script that mounts/unmounts usbs
 #
 
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
+
 OPERATION=$(printf "Mount\nUnmount" | dmenu -i -p "Choose: ")
 [ -z "$OPERATION" ] && exit 1
 [ "$OPERATION" != "Mount" ] && [ "$OPERATION" != "Unmount" ] && exit 1
-
-terminate() { notify-send -u "$1" "$2" "$3" && exit 1 ; }
 
 TMP="/tmp/tempdisks"
 # Make sure file is empty
@@ -20,7 +27,7 @@ for d in $VOL; do
     lsblk | grep "$d.*part" >> "$TMP"
 done
 
-[ -s "$TMP" ] || terminate "critical" "No usb found" "No usb were found, try again!"
+[ -s "$TMP" ] || s_notify_exit "critical" "No usb found" "No usb were found, try again!"
 
 getoption() { dmenu -i -l 10 -p "Select Usb: " < "$TMP" ; }
 
@@ -36,33 +43,33 @@ getlocation() {
 
 mountDisk() {
     sed -i '/\//d' "$TMP" 
-    [ -s "$TMP" ] || terminate "critical" "No usb found to mount!"
+    [ -s "$TMP" ] || s_notify_exit "critical" "No usb found to mount!"
     OPTION="$(getoption)"
     [ -z "$OPTION" ] && exit 1
     LOC="$(getlocation)"
     DM="$(getdisk)"
     # Check if dir is empty (make sure you don't mount on something existing)
-    cd "$LOC" || terminate "critical" "Cannot change directory to\n$LOC"
-    [ "$(ls | wc -l)" = "0" ] || terminate "critical" "Cannot mount" "Cannot mount on \n$LOC \nThere are files"
+    cd "$LOC" || s_notify_exit "critical" "Cannot change directory to\n$LOC"
+    [ "$(ls | wc -l)" = "0" ] || s_notify_exit "critical" "Cannot mount" "Cannot mount on \n$LOC \nThere are files"
     if sudo -A mount "$DM" "$LOC"; then
-        terminate "normal" "Success" "Usb mounted on\n$LOC"
+        s_notify_exit "normal" "Success" "Usb mounted on\n$LOC"
     else
-        terminate "critical" "Usb cannot be mounted, run in terminal to get more output"
+        s_notify_exit "critical" "Usb cannot be mounted, run in terminal to get more output"
     fi
 }
 
 unmountDisk() {
     sed -i '/\//!d' "$TMP"
-    [ -s "$TMP" ] || terminate "critical" "No usb found to unmount!"
+    [ -s "$TMP" ] || s_notify_exit "critical" "No usb found to unmount!"
     OPTION="$(getoption)"
     [ -z "$OPTION" ] && exit 1
     LOC="$(getlocation)"
     DM="$(getdisk)"
     if sudo -A umount "$DM"; then
         rm -r "$LOC" 
-        terminate "normal" "Success" "Usb unmounted succesfully"
+        s_notify_exit "normal" "Success" "Usb unmounted succesfully"
     else
-        terminate "critical" "Usb cannot be unmounted, run in terminal to get more output"
+        s_notify_exit "critical" "Usb cannot be unmounted, run in terminal to get more output"
     fi
 }
 
diff --git a/.local/bin/dmenu/process b/.local/bin/dmenu/process
--- a/.local/bin/dmenu/process
+++ b/.local/bin/dmenu/process
@@ -1,5 +1,14 @@
 #!/bin/sh
 
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
+
 options="shutdown
 reboot
 lock screen"
@@ -7,9 +16,6 @@ lock screen"
 choice=$(printf "%s" "$options" | dmenu -i -p "Choose:")
 [ -z "$choice" ] && exit 1
 [ "$(printf "Yes\nNo" | dmenu -i -p "Are you sure?")" = "Yes" ] || exit 1
-
-notify() { notify-send "Doom Guy says" "$1" ; }
-notifyExit() { notify-send --urgency=critical "$1" "$2" && exit 1 ; }
 
 checkDisks() {
     MOUNTEDDISKS="$(mount | tail -n1 | grep "^/dev/sd.*")"
@@ -28,13 +34,13 @@ logSysShutdown() {
 }
 shutDown() {
     logSysShutdown "shutdown"
-    notify "God Rested On The Seventh Day" &
+    s_notify "Doom Guy says" "God Rested On The Seventh Day" &
     sleep $SLEEPNUM
     shutdown now
 }
 rebootSys(){
     logSysShutdown "reboot"
-    notify "Don't Leave That Plasma Cutter Running" &
+    s_notify "Doom Guy says" "Don't Leave That Plasma Cutter Running" &
     sleep $SLEEPNUM
     shutdown -r now
 }
@@ -43,13 +49,13 @@ option() { printf "%s" "$options" | sed "$1q;d" ; }
 case $choice in 
     "$(option 1)") 
         checkDisks || 
-            notifyExit "Mounted Disks detected!" "You can't shutdown because you have mounted disks!"
+            s_notify_exit "critical"  "Mounted Disks detected!" "You can't shutdown because you have mounted disks!"
         shutDown ;;
     "$(option 2)") 
         checkDisks || 
-            notifyExit "Mounted Disks detected!" "You can't reboot because you have mounted disks!"
+            s_notify_exit "critical"  "Mounted Disks detected!" "You can't reboot because you have mounted disks!"
         rebootSys ;;
-    "$(option 3)") notify "Your screen will be locked" ; i3lock-fancy ;;
+    "$(option 3)") s_notify "Doom Guy says" "Your screen will be locked" ; i3lock-fancy ;;
     *) exit 1 ;; 
 esac
 
diff --git a/.local/bin/dmenu/sites b/.local/bin/dmenu/sites
--- a/.local/bin/dmenu/sites
+++ b/.local/bin/dmenu/sites
@@ -2,11 +2,18 @@
 
 # Sites, a dmenu script to open your favourite sites with less effort
 
-terminate() { notify-send -u "$1" "$2" "$3" && exit 1 ; }
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
 
 # Check if sites file exists
 SITESFILE="$HOME/Media/Data/sites" # Replace this with your path to sites file
-[ -f "$SITESFILE" ] || terminate "critical" "File does not exists!" "File \"$SITESFILE\"\n does not exists!"
+[ -f "$SITESFILE" ] || s_notify_exit "critical" "File does not exists!" "File \"$SITESFILE\"\n does not exists!"
 # Create the cache file
 CACHEDIR=${XDG_CACHE_HOME:-"$HOME/.cache"}
 CACHE="$CACHEDIR/sites_recent"
@@ -17,11 +24,11 @@ MOSTUSED=$(sort "$CACHE" | uniq -c | sort -rh | awk -F" " '{print $2}')
 # Combine cache with sites then output
 CHOICE=$((echo "$MOSTUSED"; awk '{print $1}' "$SITESFILE" | grep -vxF "$MOSTUSED") | 
     dmenu -i -l 10 -p "Open site: ")
-[ -z "$CHOICE" ] && terminate "critical" "Warning" "No site selected, abording..."
+[ -z "$CHOICE" ] && s_notify_exit "critical" "Warning" "No site selected, abording..."
 
 # If you wanna edit sites file use 'confs' script
 
 # Open site
-[ -z "$BROWSER" ] && terminate "critical" "BROWSER not set" "Please set BROWSER variable to continue"
+[ -z "$BROWSER" ] && s_notify_exit "critical" "BROWSER not set" "Please set BROWSER variable to continue"
 echo "$CHOICE" >> "$CACHE"
 "$BROWSER" "$CHOICE"
diff --git a/.local/bin/lk b/.local/bin/lk
--- a/.local/bin/lk
+++ b/.local/bin/lk
@@ -4,22 +4,34 @@
 # Basic script to create symbolic links for dotfiles directory more easily
 # Does not support multiple files to link
 
-terminate() { printf "lk: error: %s\n" "$1"&& exit 1 ; }
-if [ "$#" -gt 1 ]; then # if there are more parameters
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
+
+# Check if user run the script in dotfiles dir
+dotfiles="$HOME/Dev/dotfiles"
+pwd | grep "^$dotfiles" >/dev/null && s_err "You are in dotfiles directory, you can't link the files here!"
+
+if [ "$#" -gt 1 ]; then
     # use xargs to call this script with each parameter
     printf '%s\n' "$@" | xargs -I {} lk '{}' 
     exit 1
 fi
 file="$1"
-[ ! -f "$file" ] && terminate "File \"$file\" does not exist!"
+[ ! -f "$file" ] && s_err "File \"$file\" does not exist!"
 test "${file#*"/"}" != "$file" && 
-    terminate "Please go into the directory, then link the file ($file)"
+    s_err "Please go into the directory, then link the file ($file)"
 fileTypes=$(file "$file")
 test "${fileTypes#*"symbolic link"}" != "$fileTypes" &&
-    terminate "File \"$file\" is already a symbolic link"
+    s_err "File \"$file\" is already a symbolic link"
 currentDir="$(pwd)"
 currentDir="${currentDir##$HOME}"
-dotfiles="$HOME/Dev/dotfiles$currentDir"
+dotfiles="$dotfiles$currentDir"
 if [ ! -d "$dotfiles" ]; then 
     printf "%s\n" "lk: $currentDir does not exists in dotfiles directory"
     printf 'Wanna create it ? [y/n]: '
@@ -28,4 +40,4 @@ if [ ! -d "$dotfiles" ]; then
 fi
 mv "$file" "$dotfiles" && file="${file##*/}" && currentDir="$HOME$currentDir" && 
     ln -s "$dotfiles/$file" "$currentDir/$file" && exit 1
-terminate "Cannot link $dotfiles/$file to $currentDir/$file"
+s_err "Cannot link $dotfiles/$file to $currentDir/$file"
diff --git a/.local/bin/lyrics b/.local/bin/lyrics
--- a/.local/bin/lyrics
+++ b/.local/bin/lyrics
@@ -6,17 +6,25 @@
 # cmus required!
 #
 
-terminate() { notify-send -u "$1" "$2" "$3" && exit 1 ; }
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
+
 getfrom() { echo "$1" | grep "$2" ; }
 replace() { echo "$1" | sed "s/$2//" ; }
 
 # check if cmus is even running
-cmus-remote -Q > /dev/null 2>&1 || terminate "critical" "Not Running!" "Cmus is not running!"
+cmus-remote -Q > /dev/null 2>&1 || s_notify_exit "critical" "Not Running!" "Cmus is not running!"
 STATUS="$(cmus-remote -Q)"
 # get usefull information
 INFO="$(getfrom "$STATUS" " artist \| album \| title \|file")"
 # check if some music is running
-[ -z "$(getfrom "$STATUS" "status stopped")" ] || terminate "normal" "Music Stopped!" "Nothing is playing..."
+[ -z "$(getfrom "$STATUS" "status stopped")" ] || s_notify_exit "normal" "Music Stopped!" "Nothing is playing..."
 # get music name
 TITLE="$(getfrom "$INFO" "title")"
 TITLE="$(replace "$TITLE" "tag title ")"
diff --git a/.local/bin/mstat b/.local/bin/mstat
--- a/.local/bin/mstat
+++ b/.local/bin/mstat
@@ -7,15 +7,23 @@
 #    {Music name}
 # {Artist} - {Album} 
 
-terminate(){ notify-send -u "$1" "$2" "$3" && exit 1 ; }
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
+
 getfrom() { echo "$1" | grep "$2" ; }
 replace() { echo "$1" | sed "s/$2//" ; }
 
 # check if cmus is even running
-cmus-remote -Q > /dev/null 2>&1 || terminate "critical" "Not Running!" "Cmus is not running!"
+cmus-remote -Q > /dev/null 2>&1 || s_notify_exit "critical" "Not Running!" "Cmus is not running!"
 STATUS="$(cmus-remote -Q)"
 # check if some music is running
-[ -z "$(getfrom "$STATUS" "status stopped")" ] || terminate "normal" "Music Stopped!" "Nothing is playing..."
+[ -z "$(getfrom "$STATUS" "status stopped")" ] || s_notify_exit "normal" "Music Stopped!" "Nothing is playing..."
 # get usefull information
 INFO="$(getfrom "$STATUS" " artist \| album \| title \|file")"
 # get music name
@@ -37,10 +45,10 @@ DIR="$(getfrom "$INFO" "file")"
 DIR="${DIR%/*}"
 DIR="${DIR#* }"
 # go into dir
-cd "$DIR" || notify-send -u "critical" "Can't change directory" "Cannot change directory to\n$DIR"
+cd "$DIR" || s_notify_exit "critical" "Can't change directory" "Cannot change directory to\n$DIR"
 # find icon
 ICON="$DIR/$(printf '%s\n' * | grep '.jpe\?g$\|.png$' | head -n 1)"
 # If the file doesn't exists or it is empty use default icon
 { [ ! -f "$ICON" ] || [ "$(file "$ICON" | grep empty > /dev/null)" ]; } && ICON=""
 
-notify-send --icon="$ICON" -u "normal" "$TITLE" "$SUBTITLE" 
+s_notify -i "$ICON" -u "normal" "$TITLE" "$SUBTITLE"
diff --git a/.local/bin/rice b/.local/bin/rice
--- a/.local/bin/rice
+++ b/.local/bin/rice
@@ -13,15 +13,22 @@ helpmenu() {
     echo "  status   - to give some status about your bindings from your config."
     echo "  key      - to see if a key is available to map, if not will display the maps you already have."
 }
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
 
-error() { printf 'error: %s\n' "$1" && exit 1 ; }
 CLEAN="cleanup"
 getkeys() { grep -oP '^\s*\{\s*[a-zA-Z0].*\}\,' "$1" | grep -v 'NULL\|Clk\| KEY,' > "$2" ; }
 
 mddwm(){
     # select the relevant keys
     getkeys "$FILE" "$CLEAN"
-    [ -s "$CLEAN" ] || error "No keys found!"
+    [ -s "$CLEAN" ] || s_err "No keys found!"
     # clean up
     sed -i -r 's/(^\s*\{\s*)|((\"\)|\s*\})?\s*\}\,?\s*$)|(Mask|KEY|MOD,)|([A-Z0-9]*XK_)|(SHCMD\(\"?)|((\s\"))|(\{0\})|(\{\s*\.[iufv]+\s*=\s*&?)//g; s/\s\s*/ /g; s/MOD/Super/g; s/ALT/Alt/g; s/\|/ + /g; s/^0\,\s*//g' "$CLEAN"
     # get commands
@@ -61,18 +68,18 @@ mddwm(){
     done < "$CLEAN"
     # remove unnecesarry files and display message
     rm "$CLEAN" "$LAYOUTS"
-    echo Done! Markdown written in "$RESULT"
+    echo "Done! Markdown written in $RESULT"
 }
 
 keydwm() {
-    [ -z "$1" ] && error "No key provided"
+    [ -z "$1" ] && s_err "No key provided"
     # get relevant keys
     getkeys "$FILE" "$CLEAN"
-    [ -s "$CLEAN" ] || error "No keys found!"
+    [ -s "$CLEAN" ] || s_err "No keys found!"
     # get keys with input from the user
     MKEYS="matched_keys"
     grep "XK_$1," "$CLEAN" > "$MKEYS"
-    [ -s "$MKEYS" ] || error "You have no mapped keys!"
+    [ -s "$MKEYS" ] || s_err "You have no mapped keys!"
     # clean up
     sed -i -r 's/(^\s*\{\s*)|([a-zA-Z0-9]+_)|(KEY|Mask)|\s*\}\,?$//g; s/\s\s*/ /g; s/MOD/Super/g; s/\|/ + /g' "$MKEYS"
     # display keys
@@ -91,7 +98,7 @@ printkeys() {
 
 statdwm() {
     getkeys "$FILE" "$CLEAN"
-    [ -s "$CLEAN" ] || error "No keys found!"
+    [ -s "$CLEAN" ] || s_err "No keys found!"
     NCLEAN="newclean"
     # get the current keys
     grep -oP '\S\s[a-zA-Z0-9|_]+\,\s*[a-zA-Z0-9_,]+' "$CLEAN" > "$NCLEAN"
@@ -110,17 +117,17 @@ statdwm() {
 }
 
 checkdwm(){
-    [ ! -f "$FILE" ] && error "File '$FILE' is invalid!"
+    [ ! -f "$FILE" ] && s_err "File '$FILE' is invalid!"
     case $1 in 
         markdown | md) mddwm  "$2" ;;
         status   | s)  statdwm ;;
         key      | k)  keydwm "$2" ;;
-        *) error "You must provide an argument for the file! Type 'rice help' to get more information!"
+        *) s_err "You must provide an argument for the file! Type 'rice help' to get more information!"
     esac
 }
 FILE="$1"
 case $1 in
     help | h) helpmenu ;;
     *.h) checkdwm "$2" "$3" "$4";;
-    *) error "File '$1' is invalid" ;;
+    *) s_err "File '$1' is invalid" ;;
 esac
diff --git a/.local/bin/rmlk b/.local/bin/rmlk
--- a/.local/bin/rmlk
+++ b/.local/bin/rmlk
@@ -6,22 +6,30 @@
 # and add it in the current directory that this will run
 #
 
-terminate() { printf "%s\n" "rmlk: $1" && exit 1 ; }
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
+fi
+
 file="$1"
-[ -z "$file" ] && terminate "No file provided"
+[ -z "$file" ] && s_err "No file provided"
 if [ "$#" -gt 1 ]; then
     printf "%s\n" "$@" | xargs -I {} rmlk '{}'
     exit 1
 fi
-[ -f "$file" ] || terminate "File \"$file\" does not exists"
+[ -f "$file" ] || s_err "File \"$file\" does not exists"
 test "${file#*"/"}" != "$file" &&
-    terminate "Please go into the directory, then remove the file ($file)"
+    s_err "Please go into the directory, then remove the file ($file)"
 fileStatus=$(file "$file")
 test "${fileStatus#*"symbolic link"}" != "$fileStatus" ||
-    terminate "File \"$1\" is not a symbolic link"
+    s_err "File \"$1\" is not a symbolic link"
 dotfiles="$HOME/Dev/dotfiles"
 test "${fileStatus#*$dotfiles}" != "$fileStatus" || 
-    terminate "This symbolic link is not in dotfiles directory:\n$dotfiles"
+    s_err "This symbolic link is not in dotfiles directory:\n$dotfiles"
 symLinkPath="/${fileStatus#*/}"
 rm "$file"
 mv "$symLinkPath" "$(pwd)"
