source shelper in fewer lines of code

diff --git a/.local/bin/cptusb b/.local/bin/cptusb
--- a/.local/bin/cptusb
+++ b/.local/bin/cptusb
@@ -6,13 +6,9 @@
 #
 
 # Get helper script
-SHELPER="$HOME/.local/bin/shelper"
-if [ -f "$SHELPER" ]; then
-    # shellcheck disable=SC1090,SC1091
-    . "$SHELPER"
-else
-    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
-fi
+# shellcheck disable=SC1090,SC1091
+if [ -f "$SHELPER" ]; then . "$SHELPER"; else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1; fi
 
 [ $# -lt "2" ] && s_err "Not enough parameters" 
 
diff --git a/.local/bin/dict b/.local/bin/dict
--- a/.local/bin/dict
+++ b/.local/bin/dict
@@ -10,14 +10,11 @@ helpmenu() {
     echo "  add   - to add a new word in dictionary."
     echo "  edit  - to edit the dictionary file."
 }
+
 # Get helper script
-SHELPER="$HOME/.local/bin/shelper"
-if [ -f "$SHELPER" ]; then
-    # shellcheck disable=SC1090,SC1091
-    . "$SHELPER"
-else
-    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
-fi
+# shellcheck disable=SC1090,SC1091
+if [ -f "$SHELPER" ]; then . "$SHELPER"; else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1; fi
 
 BASEDIR="$HOME/Media/Data/dict" # overwrite this location
 BDICT="$BASEDIR/dictionary"
diff --git a/.local/bin/dmenu/confs b/.local/bin/dmenu/confs
--- a/.local/bin/dmenu/confs
+++ b/.local/bin/dmenu/confs
@@ -1,14 +1,9 @@
 #!/bin/sh
 
-# Get script helper
-SHELPER="$HOME/.local/bin/shelper"
-if [ -f "$SHELPER" ]; then
-    # shellcheck disable=SC1090,SC1091
-    . "$SHELPER"
-else
-    notify-send -u critical "Error" "Cannot source helper script!"
-    exit 1
-fi
+# Get helper script
+# shellcheck disable=SC1090,SC1091
+if [ -f "$SHELPER" ]; then . "$SHELPER"; else
+    notify-send -u critical "Error" "Cannot source helper script!"; exit 1; fi
 
 configs="qutebrowser $HOME/.config/qutebrowser/config.py
 quickmarks $HOME/.config/qutebrowser/quickmarks
diff --git a/.local/bin/dmenu/sites b/.local/bin/dmenu/sites
--- a/.local/bin/dmenu/sites
+++ b/.local/bin/dmenu/sites
@@ -3,13 +3,9 @@
 # Sites, a dmenu script to open your favourite sites with less effort
 
 # Get helper script
-SHELPER="$HOME/.local/bin/shelper"
-if [ -f "$SHELPER" ]; then
-    # shellcheck disable=SC1090,SC1091
-    . "$SHELPER"
-else
-    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
-fi
+# shellcheck disable=SC1090,SC1091
+if [ -f "$SHELPER" ]; then . "$SHELPER"; else
+    notify-send -u critical "Error" "Cannot source helper script!"; exit 1; fi
 
 # Check if sites file exists
 SITESFILE="$HOME/Media/Data/sites" # Replace this with your path to sites file
diff --git a/.local/bin/lk b/.local/bin/lk
--- a/.local/bin/lk
+++ b/.local/bin/lk
@@ -5,17 +5,14 @@
 # Does not support multiple files to link
 
 # Get helper script
-SHELPER="$HOME/.local/bin/shelper"
-if [ -f "$SHELPER" ]; then
-    # shellcheck disable=SC1090,SC1091
-    . "$SHELPER"
-else
-    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
-fi
+# shellcheck disable=SC1090,SC1091
+if [ -f "$SHELPER" ]; then . "$SHELPER"; else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1; fi
 
 # Check if user run the script in dotfiles dir
 dotfiles="$HOME/Dev/dotfiles"
-pwd | grep "^$dotfiles" >/dev/null && s_err "You are in dotfiles directory, you can't link the files here!"
+pwd | grep "^$dotfiles" >/dev/null && 
+    s_err "You are in dotfiles directory, you can't link the files here!"
 
 if [ "$#" -gt 1 ]; then
     # use xargs to call this script with each parameter
diff --git a/.local/bin/rice b/.local/bin/rice
--- a/.local/bin/rice
+++ b/.local/bin/rice
@@ -13,14 +13,11 @@ helpmenu() {
     echo "  status   - to give some status about your bindings from your config."
     echo "  key      - to see if a key is available to map, if not will display the maps you already have."
 }
+
 # Get helper script
-SHELPER="$HOME/.local/bin/shelper"
-if [ -f "$SHELPER" ]; then
-    # shellcheck disable=SC1090,SC1091
-    . "$SHELPER"
-else
-    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
-fi
+# shellcheck disable=SC1090,SC1091
+if [ -f "$SHELPER" ]; then . "$SHELPER"; else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1; fi
 
 CLEAN="cleanup"
 getkeys() { grep -oP '^\s*\{\s*[a-zA-Z0].*\}\,' "$1" | grep -v 'NULL\|Clk\| KEY,' > "$2" ; }
diff --git a/.local/bin/rmlk b/.local/bin/rmlk
--- a/.local/bin/rmlk
+++ b/.local/bin/rmlk
@@ -7,13 +7,9 @@
 #
 
 # Get helper script
-SHELPER="$HOME/.local/bin/shelper"
-if [ -f "$SHELPER" ]; then
-    # shellcheck disable=SC1090,SC1091
-    . "$SHELPER"
-else
-    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1
-fi
+# shellcheck disable=SC1090,SC1091
+if [ -f "$SHELPER" ]; then . "$SHELPER"; else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"; exit 1; fi
 
 file="$1"
 [ -z "$file" ] && s_err "No file provided"
