+ script helper && implementation for some scripts

diff --git a/.local/bin/csc b/.local/bin/csc
--- a/.local/bin/csc
+++ b/.local/bin/csc
@@ -1,13 +1,21 @@
 #!/bin/sh
 
-# Create script (csc)
+# Create SCript (csc)
 # This script creates a base script and it opens in your editor of choice!
 
+# Get helper script
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    printf '%s: error: %s\n' "${0##*/}" "Cannot source helper script!"
+    exit 1
+fi
 file="$1"
-terminate() { printf "%s\n" "csc: $1" && exit 1 ; }
-[ -z "$file" ] && terminate "Cannot create empty file!"
-[ -f "$file" ] && terminate "File '$file' already exists!"
-[ -d "$file" ] && terminate "Argument '$file' is a directory!"
+[ -z "$file" ] && s_err "Cannot create empty file!"
+[ -f "$file" ] && s_err "File '$file' already exists!"
+[ -d "$file" ] && s_err "Argument '$file' is a directory!"
 touch "$file"
 option="${2-sh}"
 
diff --git a/.local/bin/dmenu/confs b/.local/bin/dmenu/confs
--- a/.local/bin/dmenu/confs
+++ b/.local/bin/dmenu/confs
@@ -1,6 +1,14 @@
 #!/bin/sh
 
-EDITOR="alacritty -e nvim"
+# Get script helper
+SHELPER="$HOME/.local/bin/shelper"
+if [ -f "$SHELPER" ]; then
+    # shellcheck disable=SC1090,SC1091
+    . "$SHELPER"
+else
+    notify-send -u critical "Error" "Cannot source helper script!"
+    exit 1
+fi
 
 configs="qutebrowser $HOME/.config/qutebrowser/config.py
 quickmarks $HOME/.config/qutebrowser/quickmarks
@@ -21,11 +29,12 @@ profile $HOME/.config/profile
 functions $HOME/.config/functions
 sites $HOME/Media/Data/sites
 insults $HOME/Media/Data/insults
-this $HOME/.local/bin/dmenu/confs" # opens this file
+this $HOME/.local/bin/dmenu/confs" # Opens this file
 
 choice=$(printf '%s' "$configs" | dmenu -i -l 10 -p 'Edit config: ' | awk '{print $2}')
 [ -z "$choice" ] && exit 1
 [ ! -f "$choice" ] && 
-    notify-send -u critical "Error" "File $choice\nDoes not exist!" && exit 1
+    s_notify critical "File Error" "File $choice \nDoes not exist!" && exit 1
 
+EDITOR="alacritty -e nvim"
 $EDITOR "$choice"
