the greatest thing made in history(not finished)

diff --git a/.local/bin/qtlive b/.local/bin/qtlive
--- a/.local/bin/qtlive
+++ b/.local/bin/qtlive
@@ -5,10 +5,13 @@
 #
 help() {
     printf "Hot reload a qt application from source code.\n"
-    printf "Usage: %s [options] <qt-app>\n" "$0"
-    printf "Options:\n"
+    printf "The script will watch the source code and reload the application when the source code is changed.\n"
+    printf "It will work only for the qt applications generated by my script qtgen\n\n"
+    printf "Usage: qtlive \n"
+    printf "You don't need to specify the directory where the source code is located.\n"
+    printf "The script will look for the build directory and for the Makefile\n"
+    printf "By default it will compile with the fast version of the Makefile\n"
 }
-
 
 case "$1" in
     -h|--help|help|h)
@@ -17,3 +20,80 @@ case "$1" in
         ;;
 esac
 
+# Take the parrent folder
+PROJ_NAME="${PWD##*/}" # exactly like $(basename $PWD) but faster (why? it's fun)
+
+# Make sure the project name is not empty
+if [ -z "$PROJ_NAME" ]; then
+    echo "The project name cannot be empty"
+    exit 1
+fi
+
+# Check if the build directory exists
+if [ ! -d "build" ]; then
+    echo "The build directory does not exist"
+    exit 1
+fi
+
+# Check if the Makefile exists
+if [ ! -f "build/Makefile" ]; then
+    echo "The Makefile does not exist"
+    exit 1
+fi
+
+# Make sure inotifywait is installed
+if ! command -v inotifywait >/dev/null
+then
+    echo "inotifywait could not be found"
+    exit 1
+fi
+
+compile_and_run() {
+    # Compile the application with cmake
+    cd build || exit 1
+
+    [ -f .pid ] && kill "$(cat .pid)"
+
+    make -j"$(nproc)" "$PROJ_NAME"/fast
+
+    # Run the application
+    ./"$PROJ_NAME" &
+
+    # Save PID to file
+    PID=$!
+    echo "$PID" > .pid
+
+    # Go back
+    cd ..
+}
+
+cleanup() {
+    echo "Cleaning up..."
+
+    # Kill the application
+    [ -f './build/.pid' ] && kill "$(cat ./build/.pid)"
+
+    # Remove the PID file
+    rm './build/.pid'
+}
+
+trap cleanup EXIT
+
+while true; do
+    # Watch for changes in the source code
+    EVENT="$(inotifywait -rq --format '%e' -e modify,move,create,delete ./*cpp)"
+
+    case "$EVENT" in
+        MODIFY)
+            echo "Source code changed($(date)), recompiling and running the application:"
+            compile_and_run
+            ;;
+        MOVED_TO|CREATE|DELETE)
+            continue
+            ;;
+        *)
+            echo "Unknown event: $EVENT, doing nothing"
+            ;;
+    esac
+
+done
